const express = require('express')
const EntryController = require('./controllers/EntryController.cjs')
const CategoriesController  = require('./controllers/CategoriesController.cjs')
const ItemsController  = require('./controllers/ItemsController.cjs')
const router = express.Router()
router.get('/categories', CategoriesController.index)
router.post('/categories', CategoriesController.store)
router.patch('/categories/:category', CategoriesController.update)
router.delete('/categories/:category', CategoriesController.destroy)
router.get('/items', ItemsController.index)
router.post('/items', ItemsController.store)
router.patch('/items/:item', ItemsController.update)
router.delete('/items/:item', ItemsController.destroy)

router.get('/storefront', EntryController.index)
module.exports = router